"use client";
import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter()
    useEffect(()=>{
        router.push("/dataSample")
    },[router])
  return (
    <>
      <Head>
        <title>Next App with Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       
      </main>
    </>
  );
}
